### ISSUE TITLE
Qt6编译失败

### ISSUE THREAD

**Issue by sixsixQAQ** [vnotex/vnote#2510]
## Error
There will be two similar errors when compile it  with Qt6:

```shell
/home/sixqaq/vnote/build/src/vnote_autogen/O2QWORDHJD/moc_filesearchengine.cpp:101:1:   required from here
/opt/Qt/6.3.2/gcc_64/include/QtCore/qmetatype.h:861:23: error: invalid application of ‘sizeof’ to incomplete type ‘vnotex::SearchResultItem’
  861 |         static_assert(sizeof(T), "Type argument of Q_PROPERTY or Q_DECLARE_METATYPE(T*) must be fully defined");
```

```shell
/home/sixqaq/vnote/build/src/vnote_autogen/TSH5OOFR4B/moc_previewhelper.cpp:234:1:   required from here
/opt/Qt/6.3.2/gcc_64/include/QtCore/qmetatype.h:861:23: error: invalid application of ‘sizeof’ to incomplete type ‘vte::PreviewItem’
```

I guess it results from the change of Qt6:

```cpp
  template<typename T>
  struct IsPointerToTypeDerivedFromQObject<T*>
  {
      typedef qint8 yes_type;
      typedef qint64 no_type;

#ifndef QT_NO_QOBJECT
      static yes_type checkType(QObject* );
      static yes_type checkType(const QObject* );
#endif
      static no_type checkType(...);
      static_assert(sizeof(T), "Type argument of Q_PROPERTY or Q_DECLARE_METATYPE(T*) must be fully defined");
      enum { Value = sizeof(checkType(static_cast<T*>(nullptr))) == sizeof(yes_type) };
  };
```

In `qmetatype.h`, the `sizeof(T)` in `static_assert()` requires `T` to be an completed type.

## Solutions

1. Delete the line `static_assert(sizeof(T), "Type argument of Q_PROPERTY or Q_DECLARE_METATYPE(T*) must be fully defined");` in `qmetatype.h`
2. Include the `.h` file which contains the full declaration of  the incompleted type.

Both of these methods can solve the problem, but I don't think they are the best solutions. 

Are there any other options?

**Comment by tamlok** [comment]
It compiles fine with Qt 6.5.3. Strange!

Could you help to test to add include the header file in the two realted header files `filesearchengine.h` and `previewhelper.h`?
